name: CMake-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
      - run: |
          sudo apt update
          sudo apt install g++-10
        shell: bash

      - uses: actions/checkout@v3

      - name: Build
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        shell: bash
        env:
          CXX: g++-10

      - name: Compile
        run: cmake --build ${{github.workspace}}/build
        shell: bash
        env:
          CXX: g++-10

      - name: Test
        run: ./Meetra_v0.1.01.exe | echo 'test'


  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
