name: CMake-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build_and_compile:
    name: Build & compile on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

        include:
          - os: ubuntu-latest
            compiler: g++-11

          - os: windows-latest
            compiler: cl

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update compiler
        if: ${{ matrix.compiler == 'g++-11' }}
        run: |
          sudo apt update
          sudo apt install ${{ matrix.compiler }}

      - name: Build
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        env:
          CXX: ${{ matrix.compiler }}

      - name: Compile
        run: cmake --build ${{github.workspace}}/build
        env:
          CXX: ${{ matrix.compiler }}

#  linux:
#    runs-on: ubuntu-latest
#
#    steps:
#      - run: |
#          sudo apt update
#          sudo apt install ${{env.GCC_COMPILER}}
#        shell: bash
#
#      - uses: actions/checkout@v3
#
#      - name: Build
#        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
#        env:
#          CXX: ${{env.GCC_COMPILER}}
#
#      - name: Compile
#        run: cmake --build ${{github.workspace}}/build
#        env:
#          CXX: ${{env.GCC_COMPILER}}
#
#
#  windows:
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build
#        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
#
#      - name: Compile
#        run: cmake --build ${{github.workspace}}/build
